### ISSUE TITLE
MVP scope

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#16]
Here's what I'm thinking:

## Pages:
1. Recipe list
User sees all recipes with following details:
- title
-description
- image
- is it free or not
- can the user access it or not
- chef name (clickable to chef's page)
- ingredients

2. Recipe the user has no access to
- title
- description
- image preview
- chef name
- ingredients
- click to buy
- click to subscribe

3. Recipe user has access
All the recipe info excluding:
- buy/subscribe
- preview images

4. Chef page
- Chef name
- Chef description

5. add / edit recipe (admins only)
the simplest form with no validations.

## Signin/up
simple modal with email and password

## subscribe monthly
Do we have a dedicated sales page for this? if not we can just do a modal

## buy recipe
IMO modal is enough here

Do we need anything else?
What are your thoughts on this?

**Comment by goldylucks** [comment]
Cool thanks for the clarifications. 
Try to format it better next time, github is kinda funky ;)

some more Qs:
1. what's the purpose of the tags, categories, learning path, course type, skills, for the mvp? Since there are only 20 recipes, going over all of them takes less than a minute, no?
2. in recipeList page, if user clicks on recipe he ain't got access to, the modal appears? no page transition?
3. which kind of subscriptions are available?
4. what is "the modals sent"?
5. so buying a recipe is only available through the keychn app? why not make it available here as well?

**Comment by ASJvine** [comment]
Cool, I'll try to improve the format.. 
1. They are important, because we're currently creating content, so it's nice to already have it. I agree on your point, but people have a clear overview of it with such information.

2.  Exactly, a modal saying that he/she needs to be subscribed to access to the content. What do you think? Or you prefer [this](https://www.pannacooking.com/recipes/chilled-soba-noodles-with-lime-and-black-sesame/) approach?

3. We are defining them with Keychn Team > thinking about monthly and yearly.

4. I've sent you a mail with all the details (on March 15th)

5. Because you do not buy a recipe, you buy a spot to attend to a MasterClass with video live streaming. The VOD platform contains the recorded MasterClasses videos edited and polished. Afterwards, in the next iteration, we'll include the video live streaming in this platform and users will be able to buy a spot to attend a MasterClass.

**Comment by goldylucks** [comment]
1. I don't get it, but it's your project, so whatever you say :)
2. that link is a pretty decent approach. Let's leave that for next iteration.
4. so "modals sent" you mean the mocks of the modals you sent me on email?
5. gotcha, next iteration it is
